language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"

addons:
  apt:
    packages:
        - libmcrypt-dev

install: "pip install -r requirements.txt"

script: 
  - "python setup.py build sdist bdist_wheel test"
