language: python

python:
  - "3.6"

addons:
  postgresql: "9.6"
  apt:
    packages:
        - libmcrypt-dev

install: "pip install -r requirements.txt"

script: 
  - "python setup.py build"
  - "pytest test.py"
